name: Ruff Code Check

on:
  push:
    paths: [
      '.github/workflows/lint.yml', 
      'datacademy/**/*.py', 
      'pyproject.toml',
      'poetry.lock',
    ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out repository
      uses: actions/checkout@v3
      with:
        sparse-checkout: |
          datacademy
          poetry.lock
          pyproject.toml

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set-up pip and poetry
      run: |
        python -m pip install -U pip
        python -m pip install -U poetry
        python -m poetry config virtualenvs.create true
        python -m poetry config virtualenvs.in-project true

    - name: Install dependencies
      run: |
        poetry install

    - name: Analysing the code with Ruff
      run: |
        poetry run ruff check datacademy